name: Build RaspAP Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Raspberry Pi OS Image with RaspAP
        uses: usimd/pi-gen-action@v1
        with:
          compression: gz
