name: Build and publish RaspAP images

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-raspap-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "32-bit"
            pi_gen_version: "master"
          - arch: "64-bit"
            pi_gen_version: "arm64"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update and install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      - name: Build RaspAP Image
        id: build
        uses: usimd/pi-gen-action@v1
        with:
          image-name: "raspap-${{ github.ref_name }}-${{ matrix.arch }}"
          enable-ssh: 1
          stage-list: stage0 stage1 stage2
          verbose-output: true
          pi-gen-version: ${{ matrix.pi_gen_version }}

      - name: Upload Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: raspap-image-${{ matrix.arch }}
          file: ${{ steps.build.outputs.image-path }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
