name: Build and publish RaspAP images

permissions:
  contents: write

on:
  push:
    branches:
      - "*"

jobs:
  build-raspap-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: "32-bit"
            pi_gen_version: "master"
          - arch: "64-bit"
            pi_gen_version: "arm64"
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Custom Stage
        run: |
          mkdir -p custom_stage_raspap/package-raspap &&
          {
          cat > custom_stage_raspap/package-raspap/00-run-chroot.sh <<-EOF
          #!/bin/bash
          sudo rm -rf /etc/apt/sources.list*
          cd /etc/apt/
          wget https://gist.githubusercontent.com/ishad0w/788555191c7037e249a439542c53e170/raw/3822ba49241e6fd851ca1c1cbcc4d7e87382f484/sources.list
          sudo dhclient -v -4
          sudo echo 'nameserver 8.8.8.8' > /etc/resolv.conf
          sudo apt-get update -y
          apt-get install -y curl
          curl -sL https://install.raspap.com | bash -s -- --yes --openvpn 1 --restapi 1 --adblock 1 --wireguard 1 --tcp-bbr 1
          EOF
          } &&
          chmod +x custom_stage_raspap/package-raspap/00-run-chroot.sh &&
          {
          cat > custom_stage_raspap/prerun.sh <<-EOF
          #!/bin/bash -e
          if [ ! -d "\${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF
          } &&
          chmod +x custom_stage_raspap/prerun.sh

      - name: Build RaspAP Image
        id: build
        uses: usimd/pi-gen-action@v1
        with:
          image-name: "raspap-${{ github.ref_name }}-${{ matrix.arch }}"
          enable-ssh: 1
          stage-list: stage0 stage1 stage2 ./custom_stage_raspap
          verbose-output: true
          pi-gen-version: ${{ matrix.pi_gen_version }}

      - name: Upload Artifact
        uses: svenstaro/upload-release-action@v2
        with:
          asset_name: raspap-image-${{ github.ref_name }}-${{ matrix.arch }}.zip
          file: ${{ steps.build.outputs.image-path }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: true
